# Generated by Django 6.0.5 on 2026-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('title', models.TextField()),
                ('sentiment_bielik', models.CharField(max_length=20)),
                ('sentiment_gemma', models.CharField(max_length=20)),
                ('political_bias_bielik', models.CharField(max_length=20)),
                ('political_bias_gemma', models.CharField(max_length=20)),
                ('sentiment_bielik_explanation', models.TextField()),
                ('sentiment_gemma_explanation', models.TextField()),
                ('political_bias_bielik_explanation', models.TextField()),
                ('political_bias_gemma_explanation', models.TextField()),
                ('sentiment_gt', models.CharField(blank=True, max_length=20, null=True)),
                ('political_bias_gt', models.CharField(blank=True, max_length=20, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
            ],
        ),
    ]
